export const penjualanBarangJasaFormField = [
    {
        key: 1,
        label: "Tanggal Permintaan",
        name: "tanggalPermintaan",
        value: "",
        type: "date",
        placeholder: "Pilih Tanggal Permintaan",
        required: true,
    },
    {
        key: 2,
        label: "Lokasi",
        name: "lokasi",
        value: "",
        type: "text",
        placeholder: "Masukkan Lokasi",
        required: true,
    },
    {
        key: 3,
        label: "Unit / Departemen",
        name: "unitDepartemen",
        value: "",
        type: "text",
        placeholder: "Masukkan Unit / Departemen",
        required: true,
    },
    {
        key: 4,
        label: "PIC User",
        name: "picUser",
        value: "",
        type: "text",
        placeholder: "Masukkan PIC User",
        required: true,
    },
    {
        key: 5,
        label: "Status Pekerjaan",
        name: "statusPekerjaan",
        value: "",
        type: "select",
        placeholder: "Pilih Status Pekerjaan",
        options: [
            {
                label: "Baru",
                value: "Baru",
            },
            {
                label: "Tambahan",
                value: "Tambahan",
            },
            {
                label: "Urgent",
                value: "Urgent",
            },
        ],
        required: true,
    },
    {
        key: 6,
        label: "Estimasi Biaya",
        name: "estimasiBiaya",
        value: "",
        type: "number",
        placeholder: "Masukkan Estimasi Biaya",
        required: true,
    },
    {
        key: 7,
        label: "Biaya Total",
        name: "biayaTotal",
        value: "",
        type: "number",
        placeholder: "Masukkan Biaya Total",
        required: true,
    },
    {
        key: 8,
        label: "Cost Center",
        name: "costCenter",
        value: "",
        type: "text",
        placeholder: "Masukkan Cost Center",
        required: true,
    },
    {
        key: 9,
        label: "Sumber Anggaran",
        name: "sumberAnggaran",
        value: "",
        type: "text",
        placeholder: "Masukkan Sumber Anggaran",
        required: true,
    },
    {
        key: 10,
        label: "No. SPK / PO / SO",
        name: "noSpkPoSo",
        value: "",
        type: "text",
        placeholder: "Masukkan Nomor SPK / PO / SO",
        required: false,
    },
    {
        key: 11,
        label: "Tanggal Mulai",
        name: "tanggalMulai",
        value: "",
        type: "date",
        placeholder: "Pilih Tanggal Mulai",
        required: false,
    },
    {
        key: 12,
        label: "Target Selesai",
        name: "targetSelesai",
        value: "",
        type: "date",
        placeholder: "Pilih Target Selesai",
        required: false,
    },
    {
        key: 13,
        label: "Durasi Pelaksanaan",
        name: "durasiPelaksanaan",
        value: "",
        type: "text",
        placeholder: "Masukkan Durasi Pelaksanaan",
        required: false,
    },
    {
        key: 14,
        label: "Keterangan",
        name: "keterangan",
        value: "",
        type: "textarea",
        placeholder: "Masukkan Keterangan",
        required: false,
    },
    {
        key: 15,
        label: "Dokumen Pendukung (PDF)",
        name: "dokumenPath",
        value: "",
        type: "file",
        placeholder: "Upload Dokumen",
        required: false,
    },
];