export const registerItemFormField = [
  {
    key: 1,
    label: "Tanggal",
    name: "date",
    value: "date",
    type: "date",
    kind: "date",
    placeholder: "Masukkan Tanggal",
  },
  {
    key: 2,
    label: "Nama Barang",
    name: "inventories_id",
    value: "inventories_id",
    type: "text",
    kind: "select",
    dynamicOptions: true,
    optionsParam: "inventoriesOption",
    placeholder: "Masukkan Nama Barang",
  },
  {
    key: 3,
    label: "Nomor PO",
    name: "ponumber",
    value: "ponumber",
    type: "text",
    kind: "",
    placeholder: "Masukkan Nomor PO",
  },
  {
    key: 4,
    label: "Jumlah Barang",
    name: "amount",
    value: "amount",
    type: "text",
    kind: "",
    placeholder: "Masukkan Jumlah Barang",
  },
  {
    key: 5,
    label: "Satuan",
    name: "unit",
    value: "unit",
    type: "text",
    kind: "",
    placeholder: "Masukkan Satuan",
  },
  {
    key: 6,
    label: "Harga Barang",
    name: "unitprice",
    value: "unitprice",
    type: "text",
    kind: "",
    placeholder: "Masukkan Harga Barang",
  },
  {
    key: 7,
    label: "Nama Vendor",
    name: "mst_vendor_id",
    value: "mst_vendor_id",
    type: "text",
    kind: "select",
    dynamicOptions: true,
    optionsParam: "vendorOption",
    placeholder: "Masukkan Nama Vendor",
  },
  {
    key: 8,
    label: "Nama Unit Kerja",
    name: "mst_user_id",
    value: "mst_user_id",
    type: "text",
    kind: "select",
    dynamicOptions: true,
    optionsParam: "userOption",
    placeholder: "Masukkan Nama Unit Kerja",
  },
];
