export const userFormField = [
  {
    key: 1,
    label: "Nama Lengkap",
    name: "fullname",
    value: "",
    type: "text",
    kind: "",
    placeholder: "Masukkan nama lengkap anda",
  },
  {
    key: 2,
    label: "Email",
    name: "email",
    value: "",
    type: "text",
    kind: "",
    placeholder: "Masukkan email anda",
  },
  {
    key: 3,
    label: "NIP",
    name: "nip",
    value: "",
    type: "text",
    kind: "",
    placeholder: "Masukkan NIP anda",
  },
  {
    key: 4,
    label: "Role",
    name: "role_id",
    value: "",
    type: "text",
    kind: "select",
    dynamicOptions: true,
    optionsParam: "roleOptions",
    placeholder: "Masukkan role pengguna",
  },
  {
    key: 5,
    label: "Cost Center / Divisi",
    name: "cost_center_id",
    value: "",
    type: "text",
    kind: "select",
    dynamicOptions: true,
    optionsParam: "costCenterOptions",
    placeholder: "Masukkan role pengguna",
  },
  {
    key: 6,
    label: "Kata Sandi",
    name: "password",
    value: "",
    type: "text",
    kind: "password",
    placeholder: "Masukkan kata sandi anda",
  },
];
