name: Production Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js and Yarn
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update
          sudo apt-get install -y nodejs yarn
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: yarn build-prod
        env:
          CI: false

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ${{ secrets.SOURCE_PROD }}
          target: ${{ secrets.TARGET_PROD }}

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          script: ls